/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/check-in`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/rpe`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/trends`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/water`; params?: Router.UnknownInputParams; } | { pathname: `/coach/announcements`; params?: Router.UnknownInputParams; } | { pathname: `/coach/coaches`; params?: Router.UnknownInputParams; } | { pathname: `/coach/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/coach/messages`; params?: Router.UnknownInputParams; } | { pathname: `/coach/athletes`; params?: Router.UnknownInputParams; } | { pathname: `/coach/athletes/new`; params?: Router.UnknownInputParams; } | { pathname: `/guardian/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/coach/athletes/[athleteId]`, params: Router.UnknownInputParams & { athleteId: string | number; } } | { pathname: `/guardian/athletes/[athleteId]`, params: Router.UnknownInputParams & { athleteId: string | number; } } | { pathname: `/login/[role]`, params: Router.UnknownInputParams & { role: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/check-in`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/rpe`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/trends`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/water`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/announcements`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/coaches`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/messages`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/athletes`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/athletes/new`; params?: Router.UnknownOutputParams; } | { pathname: `/guardian/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/coach/athletes/[athleteId]`, params: Router.UnknownOutputParams & { athleteId: string; } } | { pathname: `/guardian/athletes/[athleteId]`, params: Router.UnknownOutputParams & { athleteId: string; } } | { pathname: `/login/[role]`, params: Router.UnknownOutputParams & { role: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/account${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/athlete/check-in${`?${string}` | `#${string}` | ''}` | `/athlete/dashboard${`?${string}` | `#${string}` | ''}` | `/athlete/rpe${`?${string}` | `#${string}` | ''}` | `/athlete/trends${`?${string}` | `#${string}` | ''}` | `/athlete/water${`?${string}` | `#${string}` | ''}` | `/coach/announcements${`?${string}` | `#${string}` | ''}` | `/coach/coaches${`?${string}` | `#${string}` | ''}` | `/coach/dashboard${`?${string}` | `#${string}` | ''}` | `/coach/messages${`?${string}` | `#${string}` | ''}` | `/coach/athletes${`?${string}` | `#${string}` | ''}` | `/coach/athletes/new${`?${string}` | `#${string}` | ''}` | `/guardian/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/check-in`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/rpe`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/trends`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/water`; params?: Router.UnknownInputParams; } | { pathname: `/coach/announcements`; params?: Router.UnknownInputParams; } | { pathname: `/coach/coaches`; params?: Router.UnknownInputParams; } | { pathname: `/coach/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/coach/messages`; params?: Router.UnknownInputParams; } | { pathname: `/coach/athletes`; params?: Router.UnknownInputParams; } | { pathname: `/coach/athletes/new`; params?: Router.UnknownInputParams; } | { pathname: `/guardian/dashboard`; params?: Router.UnknownInputParams; } | `/coach/athletes/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/guardian/athletes/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/login/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/coach/athletes/[athleteId]`, params: Router.UnknownInputParams & { athleteId: string | number; } } | { pathname: `/guardian/athletes/[athleteId]`, params: Router.UnknownInputParams & { athleteId: string | number; } } | { pathname: `/login/[role]`, params: Router.UnknownInputParams & { role: string | number; } };
    }
  }
}
